apiVersion: apps/v1beta1 #for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: apitest-deploy
  labels:
    app: apitest-app
spec:
  selector:
    matchLabels:
      app: apitest-app
      tier: backend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: apitest-app
        tier: backend
        track: stable
    spec:
      containers:
      - name: apitest-cnt
        image: <repo-uri>/k8sapi-test:v1
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
      imagePullSecrets:
      - name: samreg

---

apiVersion: v1 #for versions before 1.6.0 use extensions/v1beta1
kind: Service
metadata:
  name: api-svc
spec:
  selector: 
    app: apitest-app
    tier: backend
  type: ClusterIP
  ports: 
  - port: 8800 # port internal to the cluster
    #nodePort: 31800  # external access
    targetPort: http # port number or name of the container port
    protocol: TCP
